### ISSUE TITLE
got a 404 error when running 'npm install'

### ISSUE THREAD

**Issue by Childult** [uwdata/draco#85]
```
> canvas-prebuilt@1.6.11 install /data/lmh/draco-0.0.9/node_modules/canvas-prebuilt
> node-pre-gyp install

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/data/lmh/draco-0.0.9/node_modules/node-pre-gyp/lib/install.js:137:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:187:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/data/lmh/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:182:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:562:21)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:449:20)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:182:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:287:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:268:11)
node-pre-gyp ERR! System Linux 3.10.0-862.11.6.el7.x86_64
node-pre-gyp ERR! command "/home/software/node-v11.3.0-linux-x64/bin/node" "/data/lmh/draco-0.0.9/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /data/lmh/draco-0.0.9/node_modules/canvas-prebuilt
node-pre-gyp ERR! node -v v11.3.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.3
node-pre-gyp ERR! not ok 
404 status code downloading tarball https://github.com/chearon/node-canvas-prebuilt/releases/download/v1.6.11/canvas-prebuilt-v1.6.11-node-v67-linux-x64.tar.gz
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN vega-lite@3.2.1 requires a peer of vega@^5.3.3 but none is installed. You must install peer dependencies yourself.
npm WARN draco-0.0.9 No repository field.
npm WARN draco-0.0.9 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.11 (node_modules/canvas-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: canvas-prebuilt@1.6.11 install: `node-pre-gyp install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 132 packages from 67 contributors and audited 814 packages in 15.196s
found 0 vulnerabilities

```

**Comment by domoritz** [comment]
This is an optional dependency and you should be able to just ignore the warning.
