### ISSUE TITLE
asp2vl.js: "Unexpected token 'export'" error & Solution (?) that worked in my case.

### ISSUE THREAD

**Issue by see-mike-out** [uwdata/draco#94]
Hi, I encountered an error saying that 'export' token is unexpected, which seemed super weird to me.

My environment settings include
- Mac 10.15.7
- Python 3.7.x
- Node.js 10.x / 12.x
- Typescript 3.2.1 (as described in the readme)

The error message was:
```{bash}
$ ... /js/build/asp2vl.js:5
export default function asp2vl(facts) {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/hyeokkim/Google Drive/Recent Works/Message Preservation/draco-flask/app/js/bin/asp2vl:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```

_It seems like my env does not support ES6 or the building process does not recognize ES5._

So, I changed
`
export default function asp2vl(facts) {
`
(line 5 in asp2vl.js)
to
`
module.exports = function asp2vl(facts) {
`
and it works well.

I'm so sure that there should be a better/more fundamental solution but sharing this for those who might be struggling with this problem and need a quick fix.

**Comment by domoritz** [comment]
Thank you for describing your approach.
